-- Tablas

DROP TABLE IF EXISTS SGR_FACTURAS;
DROP TABLE IF EXISTS SGR_GASCLUB_GASTOS;
DROP TABLE IF EXISTS APP_COLABORADORES;
DROP TABLE IF EXISTS APP_ADMINISTRADORES;
DROP TABLE IF EXISTS APP_CUPO_HISTORIAL;
DROP TABLE IF EXISTS APP_MOVIMIENTOS;

CREATE TABLE SGR_FACTURAS (
  ID INT,
  CEDULA VARCHAR(20),
  NUMERO_FACTURA VARCHAR(30),
  RUC_PROVEEDOR VARCHAR(20),
  TOTAL DECIMAL(12,2),
  FECHA DATE,
  ESTADO VARCHAR(15)
);

CREATE TABLE SGR_GASCLUB_GASTOS (
  ID INT,
  CEDULA VARCHAR(20),
  REFERENCIA VARCHAR(30),
  TOTAL DECIMAL(12,2),
  FECHA DATE
);


CREATE TABLE APP_COLABORADORES (
  ID INT,
  CEDULA VARCHAR(20),
  CUPO_MENSUAL DECIMAL(12,2),
  SALDO DECIMAL(12,2),
  FECHA_CREACION DATE,
  FECHA_ACTUALIZACION DATE
);


CREATE TABLE APP_ADMINISTRADORES (
  ID INT,
  CEDULA VARCHAR(20),
  NOMBRE VARCHAR(100),
  FECHA_CREACION DATE
);


CREATE TABLE APP_CUPO_HISTORIAL (
  ID INT,
  CEDULA VARCHAR(20),
  CUPO_ANTERIOR DECIMAL(12,2),
  CUPO_NUEVO DECIMAL(12,2),
  ACTUALIZADO_POR VARCHAR(20),
  FECHA DATE
);



CREATE TABLE APP_MOVIMIENTOS (
  ID INT, 
  CEDULA VARCHAR(20), -- colaborador dueño del movimiento
  TIPO VARCHAR(15), -- 'ACREDITACION' | 'GASTO'
  ORIGEN VARCHAR(15), -- 'CUPO' | 'FACTURA' | 'GASCLUB'
  MONTO DECIMAL(12,2), -- cupo en acreditaciones, total del gasto si no
  SALDO_RESULTANTE DECIMAL(12,2), 
  REFERENCIA VARCHAR(30), -- 'ACREDITACION' | NUMERO_FACTURA | REFERENCIA_GASCLUB
  SGR_ID INT, -- ID en SGR_FACTURAS/SGR_GASCLUB_GASTOS; nulo si es CUPO
  RUC_PROVEEDOR VARCHAR(20), -- solo FACTURA, nulo en los demas
  ESTADO VARCHAR(15), -- solo FACTURA: 'Pendiente' | 'Aprobado'
  REGISTRADO_POR VARCHAR(20), -- cedula de quien disparo la operacion
  FECHA DATE -- fecha SGR al importar, fecha del dia al crear por endpoint
);